### ISSUE TITLE
Marking Active Advocates in ET/Basket setup

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#122]
Since one of our KPIs is focused on growing our Active Advocates, we need to discuss the best way to flag these subscribers. Currently they are in a static data extension based on an import from Blue State Digital. This means new subscribers who take an action that would define them as Active Advocates cannot be added to this data extension. 

Basket is based on preferences, so I'm voting for adding an Advocacy interest flag similar to Firefox Marketplace. We would be able to add this flag to known and new Active Advocates, and then new subscribers can also self select. 

![preference-center](https://cloud.githubusercontent.com/assets/11812272/12993607/020bbd48-d0d0-11e5-9e6d-ef8f101030c1.jpg)

You can see my full preference center here: https://www.mozilla.org/en-US/newsletter/existing/1821c5b1-0cac-4bcf-94dc-a5b617e25e41

**Comment by OpenMatt** [comment]
see https://github.com/MozillaFoundation/encryption_campaign/issues/130

**Comment by OpenMatt** [comment]
cc @valianttry

**Comment by adamlofting** [comment]
While we might want to do something with an Advocacy Flag in Basket/ET, I'd like us not to confuse this with tracking 'Active Advocates'. 

The title 'Active Advocates' has a specific meaning to us and is based on recorded behaviour rather than comms preference. Ref [KPIs doc](https://docs.google.com/document/d/17_7zMuGsFJTKOMEDOZmuakvUybE0DzZRNfntSAoOGEM/edit#heading=h.e9ponl2wikjo).

Tracking 'Active Advocates' is part of MoFo's requirements to inform the CRM plan with MoCo. In short, we need to get the behavioural data into a CRM (Salesforce) and connect this to ExactTarget.

**Comment by OpenMatt** [comment]
Shall we close?

**Comment by stephaniemcv** [comment]
Closing as we have transferred from Basket to Salesforce as our CRM.
