### ISSUE TITLE
Deliver end bumpers for beat 2

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#127]
@lovegushwa and @natalieworth will deliver these to @darrenpasemko . cc @KarinaRipper 

Jordan - right now the animation _includes_ the mozilla logo, and this is built into the animation (crypty moves and acknowledges the logo).  An ideal solution would keep this logo placement.

Ideally Jordan you could deliver this EOD tomorrow so that Darren can edit in for EOD Thursday delivery.

**Comment by lovegushwa** [comment]
Working on this now, will post a update in the next hour.

**Comment by lovegushwa** [comment]
@brettgaylor 

Made good progress on this: https://redpen.io/p/cd8fe6966aa62bf06c
Red ink is voice over we need to record if we choose that direction. Will post more context this evening, need to head out the door.

**Comment by lovegushwa** [comment]
@brettgaylor @darrenpasemko @KarinaRipper 

So really we have just two versions of the video. The Landing page version is good to go as is.
We just need to decide on how to include the URL for the Partner/Native version.

**Partner/Native v1 -**  The simplest execution is to tuck a URL under the Mozilla logo.
**Partner/Native v2 -**  We push the Mozilla logo and URL to another sceen after SCN18. Will probably change how 18 is animated since the encryption character tilts up a little to make room for the mozilla logo. Also we can use one of the other cool backgrounds with this option if we like.
**Partner/Native v3 -**  We just straight up lift part of the end card animation from beat 1. Encryption animation in SCN18 should not tilt up.

See 0:54 - 0:59
https://drive.google.com/file/d/0B2qu3ExKWIlvcGtac096ZFg2SWc/view?usp=sharing

<img width="1194" alt="screen shot 2016-02-16 at 7 53 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/13099449/23700a78-d4e7-11e5-9cd0-97f59bb4722a.png">

**Comment by darrenpasemko** [comment]
I'd go with v1. 

Or maybe the original version, with the Encrypt card following, but without the mozilla logo at the end. 

Regardless I think it's more engaging, and much cuter to watch "Crypty" interact with the Mozilla logo.

**Comment by brettgaylor** [comment]
Agree w/ Darren.  I think it's the cleanest execution, and we don't actually have room to change animation at this point.  I think we are still adding to the "brand bank" with this approach.

**Comment by lovegushwa** [comment]
@darrenpasemko @brettgaylor cc @KarinaRipper

Great, so here is where we landed:
<img width="966" alt="screen shot 2016-02-17 at 9 03 25 am" src="https://cloud.githubusercontent.com/assets/12228435/13117584/6a901380-d555-11e5-8e30-03c046418c20.png">

Darren you can get the aftereffects files here:
https://drive.google.com/folderview?id=0B20-0lpP23c0UkdEYXgwbkJsczA&usp=sharing

OR just swipe the ENCRYPT footage from this file:
https://drive.google.com/file/d/0B20-0lpP23c0TjlZeWh0TDdOQ1E/view?usp=sharing

**Comment by darrenpasemko** [comment]
Thanks Jordan!
D

On Wed, Feb 17, 2016 at 9:15 AM, lovegushwa notifications@github.com
wrote:

> @darrenpasemko https://github.com/darrenpasemko @brettgaylor
> https://github.com/brettgaylor cc @KarinaRipper
> https://github.com/KarinaRipper
> 
> Great, so here is where we landed:
> [image: screen shot 2016-02-17 at 9 03 25 am]
> https://cloud.githubusercontent.com/assets/12228435/13117584/6a901380-d555-11e5-8e30-03c046418c20.png
> 
> Darren you can get the aftereffects files here:
> 
> https://drive.google.com/folderview?id=0B20-0lpP23c0UkdEYXgwbkJsczA&usp=sharing
> 
> OR just swipe the ENCRYPT footage from this file:
> 
> https://drive.google.com/file/d/0B20-0lpP23c0TjlZeWh0TDdOQ1E/view?usp=sharing
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/127#issuecomment-185307570
> .

## 

Darren Pasemko
Director
4644 S.E. 51st Ave
Portland, Oregon, U.S.A.
97206
(646) 406-1320
www.pasemko.com

**Comment by darrenpasemko** [comment]
New Mozilla Logo, and possible image treatments...

![beat 2 yellowed desat version 021716_00060](https://cloud.githubusercontent.com/assets/16806353/13126418/3050057a-d57f-11e5-93b4-e5dcf734863e.jpg)
![beat 2 desat version 021716_00060](https://cloud.githubusercontent.com/assets/16806353/13126429/3855b80a-d57f-11e5-8e9b-78cec46dcb23.jpg)
![Uploading BEAT 2 Original 021716_00060.jpg…]()

**Comment by darrenpasemko** [comment]
Looks like the "Original Image Treatment" didn't upload in that last message. Here it is...
![beat 2 original 021716_00060](https://cloud.githubusercontent.com/assets/16806353/13126773/b398cbc8-d580-11e5-872f-8f04cc087bdc.jpg)
