### ISSUE TITLE
A/B test landing page versions 1 and 3

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#132]
@adamlofting @valianttry @alanmoo @HPaulJohnson 

A. https://advocacy.mozilla.org/encrypt/
B. https://advocacy.mozilla.org/encrypt/3/

The goal of this test is to see which version performs better for email opt-in conversions.
Traffic to these versions will be via social shares on facebook or twitter, or organic.
@HPaulJohnson any other potential sources of traffic? (earned media?)

Ideally we get this up and running tomorrow so we can take advantage of any interest or social shares created by snippet traffic.

**Comment by adamlofting** [comment]
I'm going to need a little bit more info:
- Is the social traffic being split to these two pages at source (ie ShareProgress), or is that what we want to do with Optimizely? 
- Is it _only_ social traffic we want to test? That first URL looks like the default for all traffic. Do we want to test all?
- @alanmoo (or @alicoding ) do you know if we're triggering any Optimizely conversion goals in the code? We'll need this for conversion rates as the site doesn't redirect to a thank you page.

Also, it turns out I can't login to Optimizely any more. It appears to have been linked with SSO. Not sure how long this will take to fix. 

@HPaulJohnson are you able to login to Optimizely?

**Comment by alicoding** [comment]
I don't think we have done anything other than including that script tag

https://github.com/mozilla/advocacy.mozilla.org/blob/master/pages/encrypt/index.jsx#L40-L41

**Comment by alanmoo** [comment]
+1 to Ali, I didn't do anything re: Optimizely.

**Comment by lovegushwa** [comment]
@alanmoo @alicoding  can we still make this test happen? 

@valianttry @HPaulJohnson Adam left a few questions above.

**Comment by HPaulJohnson** [comment]
I'm also locked out of Optimizely because of SSO. 

RE: ShareProgress. We are still a few weeks away from implementing that so this set of testing would be done via Optimizely.

**Comment by alicoding** [comment]
I actually never done that before and don't see anything in the donate repo to copy that

**Comment by alanmoo** [comment]
@adamlofting I'd think it should be easy enough to add some Optimizely callbacks on signup once we have access.

**Comment by adamlofting** [comment]
I've pinged a few people re Optimizely, but no reply yet. So that's our biggest blocker.

@alanmoo @alicoding the Optimizely callback is pretty simple. I'm happy to review if you can point me at the code for the encryption site. 

Here's an example from donate, but we don't need the revenue amount:

https://github.com/mozilla/donate.mozilla.org/blob/dac728cd68467699d386fce0b3e09d22a96ffb82/assets/js/analytics.js#L91-L96

So instead it will look like:

``` js
    // Optimizely conversion tracking
    window.optimizely = window.optimizely || [];
    window.optimizely.push(['trackEvent', 'advocacysignup' }]);
```

**Comment by OpenMatt** [comment]
@alanmoo or @alicoding: can you point @adamlofting to the code for the encryption site?

**Comment by alanmoo** [comment]
Sorry, missed that. It's in https://github.com/mozilla/advocacy.mozilla.org @adamlofting

**Comment by alanmoo** [comment]
Specifically https://github.com/mozilla/advocacy.mozilla.org/tree/master/pages/encrypt

**Comment by adamlofting** [comment]
@alanmoo - can we add the js snippet above to here please:
https://github.com/mozilla/advocacy.mozilla.org/blob/master/components/encrypt-signup.jsx#L50

**Comment by adamlofting** [comment]
@HPaulJohnson Optimizely access has been restored -- it was only allowing mozilla.com emails in, but this now works for mozillafoundation.org emails too.

@alanmoo I've R+'d your patch and merged it - I'm not sure how this site deploys though so may require a manual push to prod? Once this is done we can start the test.

@valianttry I'm setting up this test for all traffic, not just social, but let me know if that's wrong.

**Comment by alanmoo** [comment]
@adamlofting Once merged, it got deployed to staging at https://advocacy-mozilla-org-staging.herokuapp.com/

-Alan

**Comment by HPaulJohnson** [comment]
@adamlofting @valianttry I think we only want to do this test on non-email traffic as the landing page variations are optimizing for email address form.

**Comment by alanmoo** [comment]
Are we going to be testing the alternate version of the social page? (https://Advocacy.mozilla.org/encrypt/3)? If so, I have to update that to include the playlist, which will need a little bit of design help today. (Until now that page has been there, just not linked to unless someone got curious about the URL)

**Comment by adamlofting** [comment]
I'm closing this ticket following discussion on the stand-up.

We're setup to run tests now, but this original test doesn't make sense given where the campaign is at.

Team will scope future tests in new tickets as and when there is traffic opportunities.
