### ISSUE TITLE
Snippet performance analysis: Views and optins

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#187]
- Which Beat 1 or Beat 2 snippet yielded more video views per impression?
- Which Beat 1 or Beat 2 snippet yielded more optins per impression?

Given the importance of snippet as a channel for future beats, we should do some analysis on what we've learned from Beat 1 and 2. We've used several different snippet variants and so should have some comparative data to learn from.

@adamlofting

**Comment by adamlofting** [comment]
@valianttry could you find, or point me at the list of all the snippet IDs we've used?

Then I can look these up in Tableau, and answer the questions above.

**Comment by JessicaVondrak** [comment]
Hi @adamlofting 

Here you go:
Beat #1 
Form + video = 5534
Form only = 5539
Beat #2
Video only = 5540
Simple snippet = 5541

They are also all in a Tableau sheet labeled "Privacy Day 2016" within the Snippet Campaigns workbook.

**Comment by adamlofting** [comment]
Here are some things we can see in the data:
- Adding the form to the snippet increases email opt-in acquisition by ~40X. This is the most significant factor in these results by far. (0.38% vs 0.01% sign-ups/impressions)
- Adding the video to the snippet doesn't decrease sign-ups (but naturally does add video views). (0.38% vs 0.39% sign-ups/impressions for Beat 1)
- The video with the form, and the video without have a similar Play Rate (1.46% vs 1.63%). The difference may be caused by the difference in video styles, or the addition of the sign-up form, but no conclusion can be drawn here. However, adding the form does not appear to have significant negative affect on video plays.

Given those observations, we can answer the questions:

> Which Beat 1 or Beat 2 snippet yielded more video views per impression?

Beat 2 wins slightly with 1.63% vs 1.46%. This difference could possibly be caused the including the form on one and not the other, but most likely is just the different styles of video (especially the starting frame) appeal to different people.

Beat 2 also had a higher % of impressions allocated to the video version, so total video views was much higher. 

> Which Beat 1 or Beat 2 snippet yielded more optins per impression?

Beat 1 by a very long way. This is because Beat 1 included the optin form directly on the snippet, which was ~40 x more effective than linking people to the site to signup.

The on-snippet sign-up rate is even greater than the CTR for a standard style snippet. 

Spreadsheet is here: 
https://docs.google.com/spreadsheets/d/1dEijiaX450T3RzEAlISGBEbpy0snArnOo6i78xI2KmI/edit#gid=0

**Comment by adamlofting** [comment]
Actually - hold on this for a second... I might have been misreading how the links are tagged for the CTR.

**Comment by adamlofting** [comment]
Double checked, and this was OK. I'd missed out one of the CTR fields in the sheet, but this doesn't change the conclusions above.

**Comment by HPaulJohnson** [comment]
@adamlofting can you verify the number of opt-ins (~345K) from Beat 1? That's a lot higher than I had heard reported in other places.

**Comment by valianttry** [comment]
My guess: "Signup" is calculated as "click on the submit button" in snippet metrics (Tableau) on the embedded form. People who click the submit button then receive an email confirmation that they must click to be subscribed to our list -- so that Signup number minus our ExactTarget totals = people who didn't bother to confirm their subscription by email. @adamlofting should confirm of course.

**Comment by valianttry** [comment]
To put a finer point on it, it appears there is roughly a 50% drop off rate from people who fill in the form but then don't click "confirm subscription" in the automated signup email.

**Comment by adamlofting** [comment]
Yes, to confirm: the sign-up numbers I have are the Tableau 'Form Submission Successful' events. So this won't account for people who don't confirm the double opt-in email mechanism.

The same is true for sign-ups from our website - I'm looking at the form submission event and not the ExactTarget data. 

As both groups receive the same confirmation email, this data should be fine for comparing between snippets.
