### ISSUE TITLE
Design pledge form for beat 5 landing page

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#205]
Adapt current landing pages to contain a pledge below Video. Page should auto scroll to pledge after the video ends. We also need to modify the playlist component so it works for both 4 videos.

@valianttry  @shaghdoosti  CC @natalieworth @alanmoo 

Build ticket for this page: https://github.com/MozillaFoundation/encryption_campaign/issues/188

QUESTIONS: 
- are we modifying both the email direct version and the social version?
- should current share and opt-into email CTA's sit below the form at the bottom of the page?
- if we're modifying the social version, should we add opt-into email to the pledge form? (so users sign the pledge and opt-into email at the same time?)

**Comment by natalieworth** [comment]
I've got the .ai file that I started working on here: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0dWtwZVQ2OHNDSVU/view?usp=drive_web

**Comment by natalieworth** [comment]
<img width="626" alt="screen shot 2016-03-11 at 3 54 57 pm" src="https://cloud.githubusercontent.com/assets/14876567/13719099/d3035f32-e7a5-11e5-939b-400d0b6c7280.png">

**Comment by OpenMatt** [comment]
@lovegushwa flagging w. "needs discussion" so that we can try to get those questions for you answered asap

**Comment by shaghdoosti** [comment]
Hey -- 

a few things: 

1) We're making the pledge have one key aspect: let us know what country you're in. After seeing how much copy the page would need I'm really glad that we did! 
1. @stephaniemcv is looking at if for people who came from our list we could have an auto filled form so they could tell us which country their in but not have to give their other details again. 
2. For social it should just be template 3. 
3. The signup form for either version should be next to the video not below it. We want to maximise people who take the CTA -- that's why I think having the form next to the video would be optimal. 

Jordan I'll revise the copy and send through tomorrow -- let me know if you have any other questions.

**Comment by lovegushwa** [comment]
Posting final UI in #188 Build ticket.

**Comment by OpenMatt** [comment]
@lovegushwa I'm assuming we can close this now -- re-open if wrong.
