### ISSUE TITLE
Form submission behavior?

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#224]
From what I understand, the goal of this beat is to get people to sign up for this pledge. I'm a bit confused though as to how this differs from the existing signup form. From conversations I've had, I'm using the same form as the rest of the beats, simply swapping the "Country" field to the top. I'm unclear about the handling of the data though. Thoughts running around right now: How are we indicating that this is anything different than previously signed up for? Is it different from the back end? Are we considering people to have taken the pledge if they only sign up from a certain beat's page? What happens to the rest of the pages?

@OpenMatt @valianttry @shaghdoosti @stephaniemcv

**Comment by stephaniemcv** [comment]
For the email audience, it's not truly a signup form, more of an update your information form because they are already on the list but the list might not necessarily have the correct data. My understanding is that's why we wanted to pre-fill the form with their country and email address data so they could update it. For new people who come to the page, it should be a true signup form to get them on their list. 

I can query by url for new signups in ET and find new "pledges" that way for this beat. The trick is going to be with the current email audience, since we don't have enough time to set up an entire new trigger journey based on a new basket flag. I'll have to test an ET query based off of, clicked to the landing page and the field Modify_Date.

**Comment by OpenMatt** [comment]
@mmmavis : should we assign this one to you to close, given that Alan is PTO?

**Comment by OpenMatt** [comment]
@shaghdoosti confirms taht @stephaniemcv 's answer is correct, so hopefully that resolves Alan's questions.

**Comment by alanmoo** [comment]
@stephaniemcv then we don't have to do anything special with the form other than the auto-population of it when applicable?

**Comment by stephaniemcv** [comment]
I don't believe we have to do anything special with the form based on my chat with Pmac. However, I do want to make sure we QA this form extensively.

**Comment by shaghdoosti** [comment]
+1 on extra QA

**Comment by OpenMatt** [comment]
@alanmoo @mmmavis what are the next steps here?

**Comment by alanmoo** [comment]
If there's nothing special to do other than testing, this can be closed and testing just needs to be done

**Comment by alanmoo** [comment]
That is, testing after #223 is complete
