### ISSUE TITLE
Advocacy Q1 Review - Design deep dive

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#247]
Work with @HPaulJohnson and @KevZawacki  to develop campaign creative narrative for Q1 review deck.

**Comment by natalieworth** [comment]
@HPaulJohnson @lovegushwa I have the first 4 draft images for the beat 1-4 deep dive. I'm working right now in illustrator and then can update on the google drive when approved:
![q1_presentation_v1-01](https://cloud.githubusercontent.com/assets/14876567/14367750/ad98d6da-fcce-11e5-8081-799eff6f3c71.png)
![q1_presentation_v1-02](https://cloud.githubusercontent.com/assets/14876567/14367751/adaaf34c-fcce-11e5-8f39-2f0ea3627ca5.png)
![q1_presentation_v1-03](https://cloud.githubusercontent.com/assets/14876567/14367753/adc9a224-fcce-11e5-8439-af34080226d7.png)
![q1_presentation_v1-04](https://cloud.githubusercontent.com/assets/14876567/14367752/adbcae66-fcce-11e5-8248-de3448a193be.png)
In terms of the 'narrative' style, I was trying to incorporate more visual elements/ information design and also thought that a timeline motif could be interesting in order to help with following the beat structure and timing of the campaign. I've added the 1st slide too to provide an overview context of the campaign (but can remove if not needed). 
I'll add these to redpen too for comments: https://redpen.io/p/anb5a7b15a4d8ff133

**Comment by natalieworth** [comment]
@HPaulJohnson @KevZawacki If we have any additional data to add too (I could create some infographics with it, e.g. Andrea's note on slide 18: https://docs.google.com/presentation/d/1To4q_1tKRGWRmWIqYbfGpBnV6nUtlqEgEwIl-xE2_-M/edit#slide=id.g128098145d_2_6
