### ISSUE TITLE
Create new design variants for landing page

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#254]

**Comment by brettgaylor** [comment]
Redesign hybrid page with the following variants
1) Focus the campaign ask, simplify the language, play down the country field
2) "Take the pledge" button prominent, video present, ask users to fill in country field in a subsequent page
3) Remove video, focus only on "take the pledge" ask

**Comment by HPaulJohnson** [comment]
Sorry to be replying late. To recap our discussion from earlier today on how to proceed:
- Given lack of dev resources (and time) we will simplify tweaks and shelve some of the more design/dev solutions above for testing in future campaign. Specifically, # 2 above is out of scope. # 3 will also be saved for a future as it's not something we are comfortable without testing into it.
- We'll focus on improving the CTA from a copy perspective, along the lines of # 1 for next week's kicker. We are aiming to find a short, punchy, clear way to have visitors from email understand the value in taking the pledge and giving us their country info. @shaghdoosti and I started working on some copy in this [doc](https://docs.google.com/document/d/1beBliRDZJYkQjTkeX24dhaQtOzB6his8ax9ckDWmTbY/edit) if anyone wants to add their ideas.

**Comment by lovegushwa** [comment]
@HPaulJohnson @brettgaylor @shaghdoosti 

I set up a collaborative wire-framing doc here: 
https://docs.google.com/a/mozilla.com/presentation/d/1CX7XeOyFhbBo0RLIOHvz4fwU0ZZQgqm0Pu6j7bpYHIk/edit?usp=sharing

A few notes:
- I think this is more of a UX problem than a copy problem. People may read email, but they scan pages. 
- page 5 cuts down on the copy, placing the content on the left and video on the right let's us use on paragraph instead of 2.
- displaying name and email (but not in a pre-populated field ) makes this page feel custom, but clearly not a email opt-in, this let's us cut down on the clarification copy.

**Comment by lovegushwa** [comment]
@ScottDowne can we work together on updating the Advocacy hybrid landing page? We need to wrap it up by mid day tomorrow if possible.
https://advocacy.mozilla.org/encrypt/hybrid/4

Basically the form is not converting well, our hunch is folks might think they are opting into a new email list OR the same list again. So we're clarifying the CTA by updating copy, form should be pre-populated with Name and Email.

<img width="1004" alt="screen shot 2016-04-12 at 1 34 53 pm" src="https://cloud.githubusercontent.com/assets/12228435/14499784/75c488aa-0154-11e6-9b1b-cd4aed6849aa.png">

Bonus, if you have time it would be great to make this version where name and email are displayed but not in the form so this page looks less like a email opt-in. Not necessary, but if you can swing it we can set up a AB test.  
<img width="1007" alt="screen shot 2016-04-12 at 1 35 00 pm" src="https://cloud.githubusercontent.com/assets/12228435/14499885/c81cee1c-0154-11e6-857f-e214a82aaf2a.png">

Swipe the copy here: 
https://docs.google.com/a/mozilla.com/presentation/d/1CX7XeOyFhbBo0RLIOHvz4fwU0ZZQgqm0Pu6j7bpYHIk/edit?usp=sharing

CC @simonwex @alanmoo @stephaniemcv

**Comment by stephaniemcv** [comment]
This comment is more for posterity than anything, but @shaghdoosti and I agreed that something that would have been good to test is the button copy. "Update my information" because that's the action we want them to take versus something like, "Yes, I want to be an Encryption Champion!"

**Comment by ScottDowne** [comment]
Copy changes are on staging. https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/hybrid/4

We can push that to prod after it checks out.

There was a build issue last night so I couldn't get it up until this morning. It was a unique situation and shouldn't happen again.

Leaving this open because I knew there were some other things that could be done here.

**Comment by stephaniemcv** [comment]
@ScottDowne 
The information flyout box, it looks like there is spaces missing after the periods. Other than that, looks good.

**Comment by ScottDowne** [comment]
@stephaniemcv what is an information flyout box?

**Comment by brettgaylor** [comment]
Done
