### ISSUE TITLE
Ship rough cut for video 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#45]

**Comment by rohanporteous** [comment]
Hey @OpenMatt, they guys in Syd currently have the video scheduled for a Jan 23 shoot which means the rough cut would come later of course. Is this OK or did you have a different understanding?

**Comment by OpenMatt** [comment]
Sorry @rohanporteous -- I just filed it wrong. Our understanding is that this will ship Jan 29.

**Comment by brettgaylor** [comment]
Approval:
- [ ] Brett

**Comment by brettgaylor** [comment]
Current delivery scheduled for Tuesday January 26th

**Comment by OpenMatt** [comment]
@rohanporteous still on track for rough cut by Jan 26?

**Comment by rohanporteous** [comment]
@OpenMatt @brettgaylor @valianttry yes indeed! Came in this morning for the first look after the guys wrapped on the weekend and it looks like it will all come together pretty well! As it often happens with the edit, I'm finding it might change from the storyboards/exact way it was shot just to keep things a bit tighter throughout, but looking forward to you seeing it.

I already have most of it in place, so I might be able to get it to you before COB tomorrow, earlier than planned. (Thinking it might be good getting you a version before any detailed graphics compositing work is done, as that's always much more time consuming to change).

Anything else you need, let me know.

**Comment by rohanporteous** [comment]
@OpenMatt @brettgaylor @lovegushwa @valianttry 

Hey all! 

You can find the initial rough cut here: https://drive.google.com/a/agency.sc/file/d/0B3UIshL1Uom0SFNueXdwRVJXaU0/view As a rough there are of course many things still left to do. The notes below should hopefully make everything as clear as possible!

As always, the best feedback is that which is really focused, and taking into account the need to turn this around really quickly. If the changes aren't too major, I think we'll be able to have most of it locked by Friday, leaving us to simply focus on the sound effects/mix and possibly some social graphics next week.

Be great if you can get feedback to me tomorrow!

R

—

## Overall notes:

### Main things to review:

Story, pacing, edit, music, audience understanding of messages/moments.

### Things yet to be worked on:
- **Graphics**: only the first two scenes have been worked on as examples of what they'll be like throughout. The rest are just placeholder, and will be made to work for the shots. I didn't want to do any more as it's much better to work on them once the edit's locked for efficiencies sake. The end screen also hasn't been worked on.
- **Color grade**: the shots haven't been graded at all, so appear more muted than they will in the final version.
- **Sound effects & mix**: there hasn't been anything added to this at all, so it's just the raw VO, on-set sound and music. SFX will really bring all of the moments together, with each message having it's own alert sound/swooshes etc. The other moments like the quieter office scene will also sound much better.
- **VO recording**: this version is still just the initial audition. Any notes on her performance are welcome for the next recording!
- **Small fixes**: The second shot already includes people removed from the background for continuity, but there might be more examples of these things we can fix throughout. (Most noticeably in my mind: hiding the obvious Apple logo in the final office shots with a plant/object on the desk). The Australian native trees at the start might not be absolutely ideal, but unfortunately this is not something I can fix in post ;)

## Additional context:

**Length of scenes**: as is often the case I've found things worked slightly differently in the edit than how they were storyboarded. This mostly meant a streamlining of shots, and making each moment simpler to understand what was happening in a clearer way. The biggest switches here were cutting the receptionist looking at the exterminator's moment (didn't work so well with the split outdoor/indoor scene in the edit) and simplifying the office glares at the end. 

**Narration**: the edit also made it clear that there potentially wasn't enough narration to span the entire video without some awkward pauses. I think it'd therefore work to insert some funnier quips into the vid. I've included some examples of what I think could work in subtitles below (for the new joke about the dad leaving the stroller and the exterminator's celebration), but it could be good to have a bunch of lines to try, and maybe get the voice actor to improvise some as well. I think we'll want to get her reading the URL as well at the end won't we?

**Intro**: I thought it was perhaps good to start fairly natural with a messaging sound (I didn't add that current one in, that was already there… the actual one would be right at the start) and only have the music come in once the narrator has introduced the premise and the woman realizes what's going on: the mischief begins. That said, I think the timing of the message appearing and the scene overall might have to be tweaked. 

**Music**: we actually managed to get a composer to work on this vid, making a quirky digital score somewhat similar in tone to another video by the same guy in the Slack one, the promo for Coin: https://www.youtube.com/watch?v=w9Sx34swEG0 (PS are there any tech videos that guy isn't in? Here's one for another CC company: https://www.youtube.com/watch?v=8ZtG5DX5FR0). I've done a rough edit of his score to make it fit, but he would do another polish before final of course. I think it seems to fit the tone! Be great to hear your take.

**Comment by rohanporteous** [comment]
@OpenMatt permissions fixed ;)

**Comment by valianttry** [comment]
cc @shaghdoosti

**Comment by OpenMatt** [comment]
Document for gathering feedback: https://docs.google.com/document/d/1y_tLAXPdIV_x1KGp0zjJv0V3M_rgbaJ5sJoiUNTNzUw/edit

**Comment by rohanporteous** [comment]
FYI my notes during the call with @brettgaylor (for context, he saw an additional rough edit): 

We’re getting there. Like’s the first cut better. Needs an overall tightening. What does it look like to lose one of the interactions—can we get it to the 45 second mark? But let’s only discuss that if other tightening doesn’t work.

Exterminator and the Dad. Can’t see that the exterminator sees the CC details. Look into other shots.

Did like the idea to fill some of those spaces with dialogue. Create a document for the team to brainstorm.

Like the dance over the biting of the knuckle. Cut to the secretary is better than expanded scene.

Boss isn’t quite working—what’s his reaction? ‘Why’s my son’t poop blue’ only works for a comedic performance. Could use other message text.

Play with timing at the end. Way Brett imagining it working was that the narrator created the snap back to reality moment. Something like ‘Let’s not live in that world’. Could do the ‘allow you to be you’ line over people working in the office, or in titles.

Some feedback was that people couldn't read the emojis in the first message. They weren’t on screen long enough. Think it might actually be because a bunch has to be assumed in the text. Talked about adding emojis to the woman's reply, but that just adds more to unpack when all we need from her is the tone of her response. Want to be super clear, could add the text ‘baby’ and have baby/bottle emoji at the end.

Lose the dad’s eyeroll to speed things up. Or use the second one? Don’t need the wider establishing shot, keep it to the first edit.

Generally aim to cut to 45. (Might need the removal of one character). Might be too much, but something to aspire to.

Music was a little too dance party/EDM at the opening. But otherwise good throughout.

Final scene doesn't work between boss/office. Can the moments be connected somehow? Have his message relate to his staff and then have him be overwhelmed by all their personal messages? Have another look at the boss’ expressions and spit them out to Brett?

**Comment by rohanporteous** [comment]
Hey @brettgaylor @valianttry @OpenMatt @shaghdoosti, I've been working on a new rough draft following my conversation with Brett this morning and just wrapped up. I think it's working a lot better!

### You can find the two options (with/without leaving baby behind) [here](https://drive.google.com/file/d/0B3UIshL1Uom0WXJhWThpamFBQ28/view?usp=sharing) and [here](https://drive.google.com/file/d/0B3UIshL1Uom0WFJUX3BKemh5b2c/view?usp=sharing).

The main things that have been altered are:

**Timing**: I've tightened all moments across the board. Where the final office shot finished at 1:00, it now finishes at 50 seconds (for the one without leaving the baby). Tom will certainly miss that scene, hence including both, but I think removing it does help pacing. Some of the other ways I cut it back was to add some stylized speed ramping (a type of fast forward) to the exterminators’ scene which hopefully both gives it energy and keeps things moving.

**Narration**: I gave the narrator more control of the world, so the messages only start to show when she prompts them at the start ('imagine a world'), and added the ‘soo, let’s not’ at the end to prompt the finish of the fantasy. (While I’m not 100% sure that’s the best line, I think something that short and snappy is ideal).

Another slightly more subtle change to the narration that actually makes a huge difference is the timing. In the previous edit she actually said each point noticeably after the graphics appear, meaning it was more work for the audience to interpret what was going on. She now introduces each scene/moment _beforehand_, taking a lot of the work out for the audience, and making each scene run more smoothly from the perspective of understanding.

**Ending**: I changed the ending to tie into the VO more, ‘cheating’ a shot that was intended for the start of the video by making it into something else entirely: the alternative/ideal reality to contrast the bulk of the story where messages aren’t displayed, and people just go about their day. The timing of the edit also works nicely for ‘you to be you’ as the walk onto the screen, one after the other. (Will likely have to create a better/more styled version of the rewind effect or have a slightly different approach, but let me know what you think).

**Small fixes**: beyond those large switches, I also worked through some smaller changes—the exterminator seeing the CC details a little better and the mother's text message, for example—but still need to finalize the boss' graphic and the final title frames with the other doc.

Looking forward to chatting tomorrow(/later today)!

**Comment by brettgaylor** [comment]
Thanks, @rohanporteous !

I think I agree rough3b edit - the forgetting stroller moment is good, but pacing is better without it.  I also think that the pause with the exterminator/dad is still too long - we seem to be waiting for the music to hit a beat, but I don't think the payoff is worth it in this case.  I think 

Can you try the slide ins in all of the transitions?  I find the cuts at :15 and :22 awkward, and it could help make things seem more speedy.

The rewind idea seems to be working, though I'm not sure we gave the office workers enough of a chance :)  I'd still like to see a version where we quickly end after the narrator makes their texts disappear.

If we go with the current edit, I don't find the shot at the end of the dad/woman particularly engaging, but I think it works well enough. 

I can do voice later this evening if needed!

**Comment by rohanporteous** [comment]
Thanks @brettgaylor! Quickly on your points:

**Dad/exterminator**: I think this will be made better with SFX announcing the awkwardness of the CC reveal, but perhaps it just needs a little fill from the narrator? 'Ummmmm…' or 'Ahhhhhh…' to highlight the awkwardness and make it deliberate, rather than have the moment feel slow.

**Slide/wip**: will try! But also don't want it to become overkill/too much.

**Office**: will give them a moment longer to relax back into work.

**Endings**: will do exports with/without the rewind/people. As a side note this shot will be flipped to match the start, which might make it better… walking towards the right. Feels like moving on. Similarly it might be because it hangs there a little too long, and perhaps we should cut to the background on the CTA/URL.

**Timing**: generally feeling better about the timing pacing?

**Comment by rohanporteous** [comment]
@brettgaylor @HPaulJohnson: have tried two new things here.
1. [Switching the CC/poop text](https://drive.google.com/file/d/0B3UIshL1Uom0R0ZOQ04tMEthNjg/view?usp=sharing). Had to change the way it worked with the dad as the emphasis wasn't on the CC# reveal during their stare off anymore, so it's shorter overall. The boss' lines would have to be simpler. Remove the diaper line to just have something like 'Credit limit exceeded' in the first shot, and maybe '$50,000 owed' in the second. (Needs to play on his look of disgust. 
2. [Switching the text, and trying a different end](https://drive.google.com/file/d/0B3UIshL1Uom0bkVEREgyc252Xzg/view?usp=sharing). This end gives the scene a little more room to breath, and doesn't deal with the boss' awkward look. I used a take with Tom in it as his sharp movement actually helps to accentuate the disappearing of messages a bit more for a stronger overall reaction, and we just cut back to the boss once everything returned to normal. Allowing 'him to be him'. (Think his initial text could just say something like 'Credit limit exceeded' and not have the reaction due to the bigger moment happening all around him). 

What do you think of both?

**Comment by rohanporteous** [comment]
@brettgaylor @HPaulJohnson any thoughts on these? Would love final direction chosen ASAP as the voice artist can record as soon as we're ready, and I'd love to get that done early so it doesn't fall to after the weekend.

**Comment by brettgaylor** [comment]
@rohanporteous just consolidating, will get back to you within hour

**Comment by rohanporteous** [comment]
@brettgaylor great. Feel free to bring me into any calls if useful.

**Comment by brettgaylor** [comment]
@rohanporteous ok, so we like these new edits. Feel they are working well - go with both. Nice work, we may have saved the boss!

Notes:
-Please change "poo" to "poop". :hankey: 

-Instinct is good to change the angle of the dad's search, but if you could cheat it a bit more - for me it's just a bit weird on the current angle, almost looks like a mistake.

-I do think a wipe would help the transition at :23 - can you try?

-@HPaulJohnson is going to consolidate both the final voiceover, onscreens and end text in #83 - he's just wrangling that now.  Only large note there is that we don't want the boss to be overdrawn in his account, we just want to highlight his credit card information.  We want him to be purchasing a "boss of the year" mug.

**Comment by brettgaylor** [comment]
@rohanporteous I also feel like we can still tighten this edit a bit in fine cutting, and add some sound effects to make it a bit punchier.  Here's some fine cut notes and audio ideas.

-head of :13 - cut on her leaving, right on his big obvious blink
-right on that cue, a subtle baby crying
-:25 - sound of a huge crowd
-:31, right when she sighs, see if you can record a little "mmmmkay??" sound for the background, make it subtle. Here is the chance for another Tom cameo.
-:36 tighten head of this shot, so she is already looking over her shoulder at the beginning
-add some cashier sounds/potentially the sound of a credit card transaction/modem sound

Happy polishing!

**Comment by rohanporteous** [comment]
Hey @brettgaylor, thanks for these. I think they're all pretty doable. Sound effects are still to come of course so it will be punchier throughout the entire video, but they're good notes/ideas to pass on! A few comments/questions:
- Cut just before the blink (just worked a bit better), and shortened some of the dad edit to match. 
- Over the shoulder: you mean the secretary right? (Not the girl in the office later). It was done this way so that she had a quick moment of realizing that the boss is looking at her, before picking up the trouble with the message. It feels a little rushed to cut the start to over the should entirely, as unfortunately we can't hold on her wide eyes for a little longer—she keeps moving her head around instead of staying on the performance. Was there a particular thing you were concerned with here?

**Comment by rohanporteous** [comment]
Hey @brettgaylor @HPaulJohnson @valianttry @lovegushwa, I've worked through a bunch of the clips and have something for you to preview over the weekend if you want.

A lot of the graphics have been added, and the color of the shots has been adjusted to be a lot richer. SFX are still yet to be done in any way, and the composer should be able to tighten up the score as well.

I only did a few graphics for the final office shot for the moment, as I wasn't sure if it was too much or not to have them all moving (compared to messages lined up in static rows), and given it can be a bit time consuming I thought it's best to preview it first. 

You can see my first export [here](https://drive.google.com/file/d/0B3UIshL1Uom0ajVKUWNRc3l3b3c/view?usp=sharing) and another shorter edit [here](https://drive.google.com/file/d/0B3UIshL1Uom0X2VrR1FuUG5MMWc/view?usp=sharing) that I trialled quickly… it removes the first cut to the boss, and bits of the first and second scenes. 

Let me know what you think!
R

PS on timelines, I'll be away all day tomorrow (crazily catching a 3am bus to the snow) but might be able to do some extra work Sunday if necessary. Otherwise I'll be squeezing work in Monday morning or completing it upon landing in Sydney on Wednesday.

**Comment by rohanporteous** [comment]
Oh, for reference: https://www.dropbox.com/s/rsgbfk1w9y36b6j/Screenshot%202016-01-29%2022.32.13.png?dl=0

**Comment by brettgaylor** [comment]
Thanks!

So some of my fine cutting suggests helped, but most didn't. :hankey: 

-It was better when music started with narrators "imagine a world" vs right at start
-In "moz.edit.graphics.1.short.mp4" the later start to the shot works, but try cutting _after_ he blinks
-The secretary worked better how you had it in the previous edit - I miss the dad at the window
-Why does her mainsplaining search lose the background? I find this a bit distracting
-at :32, with the boss leaving the office, the graphics here aren't quite working for me.  Could we:
1) actually show a picture of the boss of the year mug
2) Make sure that the credit card info is super prominent and never leaves screen with his movement?

-I think the texts/searches on the office workers screen should probably just stay on one plane - it's distracting to have them move around, especially once you add all of them (confirmed for me by the reference PNG you sent)

-I also wonder if we couldn't just end here when they go back to work, if you have the handles in that shot.  The boss is OK, but less of a strong closing

-Can we wipe the text on screen, or think of a good transition there?

really coming together with each edit!  

PS apologies for level of detail, i've spent way too much time as a final cut jockey ;)

**Comment by rohanporteous** [comment]
@brettgaylor 
1. Yes, I agree.
2. Yep.
3. Assuming you mean boss at the window… can keep as it was.
4. The rationale behind losing the background was that she was typing into a a search bar, but it's only after she clicks 'search' that anything would be tracked, not when she's writing. The the animation is trying to hint at the results page rather than the search bar itself which wouldn't be a privacy issue unless there's some keystroke monitoring I'm not aware of. I think this would be reinforced with the SFX of the button press etc, but is there some other way you'd like this to be handled better? Could just change the background a bit to make it obvious it's transitioned, which will be easier with the new rectangular search bar. @lovegushwa ?
5. Will try both! Might add to the things people have to understand if we have the image, as that would take visual priority over the shopping cart and it might take longer to realize it's a purchase, and framing might make the second point a bit more difficult. Would be good to know why you think it's not working rather than just the solutions you want to try so we can make sure we're on the same page.
6. Yep, was thinking the static graphics in the office might be better. 
7. What text are you referring to here? If the office scene, the logic would be that they were appearing while we're on the boss (hence all the message sounds/his motivation to look up). If #Encrypt, we're waiting on final graphics from @lovegushwa as they weren't approved, so haven't spent any time on animating this yet as it could change.

**Comment by rohanporteous** [comment]
Hey @brettgaylor @lovegushwa, I worked on a couple of those this afternoon and have uploaded a new version (accidentally video only) [here](https://drive.google.com/file/d/0B3UIshL1Uom0RFBSeUlBSi0tMWM/view?usp=sharing). It covers:
1. Music starting in the right spot.
2. Cutting after he blinks/
3. Kept boss at window.
4. Square search bar (Jordan's request—haven't yet dealt with new background, let me know your thoughts on that idea Brett!)
5. Made smaller and changed animation so CC# is in shot for the majority of this time. Let me know your thoughts on this one and RE pic, above.
6. Yet to change graphics, but mostly underway/easy to implement.

I also sent the edit to both our composer and SFX designer/mixer so should have those back to work with shortly. 

I'll be working on the final changes before my flight tomorrow. Can check in in your morning if you want, and send you through updates before I fly!

Thanks,
R

**Comment by lovegushwa** [comment]
@rohanporteous this is looking really good! 
I'm digging the updates, your original rectangle search box is way better.

I few final suggested tweaks: 
- I'd like to knock the saturation down on the bright green interface elements just a hint. 
- I was looking at how sandwich uses transparency at times to make the interface elements feel a bit more integrated into the environment, I think we could use the same treatment in a few scenes.

<img width="933" alt="screen shot 2016-01-31 at 8 57 14 pm" src="https://cloud.githubusercontent.com/assets/12228435/12709146/a859cff8-c85d-11e5-9c50-3d53115c3b27.png">

**(my quick fake version)**
![motion-effects-c](https://cloud.githubusercontent.com/assets/12228435/12709323/9164a582-c85f-11e5-9e12-70e64f675927.jpg)

**(a few other moments where a tiny bit of transparency might work well)**
<img width="1348" alt="screen shot 2016-01-31 at 8 56 20 pm" src="https://cloud.githubusercontent.com/assets/12228435/12709259/ee25b82a-c85e-11e5-857e-994ffed33c51.png">

<img width="1353" alt="screen shot 2016-01-31 at 8 56 30 pm" src="https://cloud.githubusercontent.com/assets/12228435/12709260/f59a76a4-c85e-11e5-8136-d1f8ebe48cad.png">

<img width="1351" alt="screen shot 2016-01-31 at 8 56 54 pm" src="https://cloud.githubusercontent.com/assets/12228435/12709264/f97cb250-c85e-11e5-8e39-3c48e7f64208.png">

**Comment by brettgaylor** [comment]
Hey @rohanporteous yes looks good, but as you say video only :)  Update with sound and I can check in again.

What do you think, cc @lovegushwa, about showing a picture of an actual boss of the year mug in the boss' purchase?

**Comment by lovegushwa** [comment]
@brettgaylor regarding the boss of the year mug. If we can make it work ... it reads and does not feel too disconnected from the other UI elements ... I think it could add a funny kick.

http://www.cafepress.com/+boss+mugs?page=7
![screen shot 2016-02-01 at 10 01 21 am](https://cloud.githubusercontent.com/assets/12228435/12726198/3258e8fc-c8cb-11e5-8473-a54d7ce31f3e.png)

**Comment by rohanporteous** [comment]
Hey @brettgaylor @lovegushwa, I've done the following [in this new version](https://drive.google.com/file/d/0B3UIshL1Uom0bkVVTVRIdV9uWEk/view?usp=sharing):

1) knocked down saturation of green
2) made all 90% opaque
3) changed to static graphics at the end
4) made all edit requests
5) changed to WBB mug (removed shopping cart as there was just too much information, and changed text so it didn't repeat the joke and so it made what was happening clearer. It's definitely more about the mug joke now than the issue of CC privacy breach, but your call.

Unfortunately the boss at the window blinds went offline during export… that will obviously be fixed next time.

This video also include the first rough take on the SFX. While the sound designer was trying to use non-Apple SFX to avoid any infringements, I think it's all a little bit too glitchy/techy overall, especially with the music. My feedback would be to make most of the messages normal swooshes/typing sounds, button clicks etc (in the secretary scene, for example) with small highlights for each notification like the cashier, email alert and so on. I also don't really know if the crowd is working, or if it's too clear that there are a bunch of notifications popping up in the boss scene.

Be great to know what you think!

Separately the composer's also worked on [a polish of the score](https://drive.google.com/file/d/0B3UIshL1Uom0WXdNRzN6R1h4SDA/view?usp=sharing), which works a lot better than previously. (He and the sound designer were working at the same time, so it's not incorporated into the other mix just yet). I unfortunately don't have time to export another version right now, but hopefully that will give you a good sense of it!

Let me know any feedback when you get a moment and I'll try to check back in from LAX.

Thanks!
R

**Comment by rohanporteous** [comment]
Just about to board but thought I'd give you the sound designer's reply for a bit of additional context for your feedback:

_After listening with fresh ears this morning I tend to agree. What I'll do is strip them back and create a distinctive electronic chime sound reminiscent of the various messenger apps - it'll have to be original but I'll aim for less tech and more chime. If we use the one sound throughout it will probably work better as it will become more of a motif and therefore help with the offscreen boss scene at the end as it will have been established. That combined with the typing app sound (I used this in the first scene) and a few context sounds where appropriate could work._

_I think I like the crowd, but it definitely jumps out and breaks the smooth flow of the rest of the mix. It depends if we want to achieve this intensity or tone it back. A weaker crowd will sound wrong in the context, but maybe I can try pulling it back in the mix a little for the next version._

**Comment by valianttry** [comment]
This is really looking good. may have been answered in the epic back-and-forth -- but the very first popup bleeds off screen, and looks like a mistake:

![moz_edit_graphics_3_mp4_-_google_drive](https://cloud.githubusercontent.com/assets/9830371/12733370/3df40560-c8ef-11e5-9f20-f9b4c29f10b5.png)

The first time you're able to read it, the dad's reaction is happening. You can miss his reaction.

**Comment by lovegushwa** [comment]
@rohanporteous @brettgaylor @valianttry 

I think the popup is working better now than it was in previous versions when less was showing, we could also remove it all together? (You see it for the first time when you also see the dad.) **@brettgaylor @rohanporteous what's your thoughts on this?**

Also **@brettgaylor whats your take on the mug?** Keep it?

**Comment by rohanporteous** [comment]
Hey Andrea, the issue was the framing in the first shot… it works timing
wise to bring it up earlier when the narrator introduces the premise, but
if you have it small enough to be readable on that screen it's far too
small on the wide, and if you show too much the viewer will think they're
meant to be reading it and struggle. This was an attempt to show something
appearing, but make the viewer feel confident they're not meant to see what
it says just yet—they find out when she finds out!

Not 100% ideal but trying to be the best balance of a number of factors.

On Monday, February 1, 2016, lovegushwa notifications@github.com wrote:

> @rohanporteous https://github.com/rohanporteous @brettgaylor
> https://github.com/brettgaylor @valianttry
> https://github.com/valianttry
> 
> I think the popup is working better now than it was in previous versions
> when less was showing, we could also remove it all together? (You see it
> for the first time when you also see the dad.) _@brettgaylor
> https://github.com/brettgaylor @rohanporteous
> https://github.com/rohanporteous what's your thoughts on this?_
> 
> Also _@brettgaylor https://github.com/brettgaylor whats your take on
> the mug?_
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/45#issuecomment-178260780
> .

## 

Rohan Porteous
Creative Director

http://agency.sc
The creative studio for social change · Sydney · New York
office +1 (646) 583-1538 · cell +1 (646) 932-7169
address  601 West 26th #325 · skype rohanporteous

**Comment by rohanporteous** [comment]
@brettgaylor @lovegushwa any feedback on SFX/music? Will be able to get
changed/alterations overnight if you can get it to me now to forward
on… will be more difficult once I'm back/closer to deadline.

(If you can't get it in the next hour or so send it through to Ben our
production manager at benjamin@agency.sc and he'll be able to pass it on).

On Monday, February 1, 2016, lovegushwa notifications@github.com wrote:

> @rohanporteous https://github.com/rohanporteous @brettgaylor
> https://github.com/brettgaylor @valianttry
> https://github.com/valianttry
> 
> I think the popup is working better now than it was in previous versions
> when less was showing, we could also remove it all together? (You see it
> for the first time when you also see the dad.) _@brettgaylor
> https://github.com/brettgaylor @rohanporteous
> https://github.com/rohanporteous what's your thoughts on this?_
> 
> Also _@brettgaylor https://github.com/brettgaylor whats your take on
> the mug?_
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/45#issuecomment-178260780
> .

## 

Rohan Porteous
Creative Director

http://agency.sc
The creative studio for social change · Sydney · New York
office +1 (646) 583-1538 · cell +1 (646) 932-7169
address  601 West 26th #325 · skype rohanporteous

**Comment by lovegushwa** [comment]
@rohanporteous I'm ok with the music. I agree that the SFX is overly glitchy/techy. 
CC @brettgaylor 
- In the first scene, I think the buzz noise is enough.
- I would really really tone down artificial computer magic sounds (the sound 0:15 for example.)
- I'm on the fence about the baby cry. It could be more subtle. 
- I think sticking to natural sounds like keyboard typing in the office is a better fit.

**Comment by lovegushwa** [comment]
@rohanporteous again I think Sandwhich is a good benchmark. The UI in the environment is silent.

**Comment by valianttry** [comment]
Sure, I get the problems you're trying to solve for, but because it is in the very first shot of a popup it's not clear that it's not supposed to be read. (Which is why viewers might struggle and think it's a mistake.) I don't think you lose anything if it instead first appears as the shot changes to include the dad. Her reaction alone could work before it is readable. Sorry to keep asking about this but I do think it looks odd  if you've never seen the video before or don't know the premise at all (which hopefully will be a large # of people).

**Comment by brettgaylor** [comment]
@valianttry @rohanporteous let's leave the opening - Andrea we're introducing a bit of curiosity before the narrator finishes "imagine a world". It works for me.

The music is indeed working better!  Like it.

I think your instincts on the SFX are correct - it's a bit too much at the moment, and to generically "tech" vs more believable modern phone UI.  The UI should be silent.

The non-diegetic sounds like the crowd do seem to stand out - I think something subtle with a crowd might have worked - if you want to have Ben try something subtle for a last attempt I can review again today, or otherwise just cut it.

Boss of the year works - how crazy would it be to try and get the ACTUAL BOSS on that mug? 

Sorry for late feedback, Rohan - was only able to get to this in the morning.  Sounds like we're on same page re: sounds.

Really shaping up well!  Are we not displaying any CTAs on screen though? @HPaulJohnson

**Comment by HPaulJohnson** [comment]
@brettgaylor on-screen CTA's being worked on here: #85

**Comment by rohanporteous** [comment]
@brettgaylor @HPaulJohnson @lovegushwa I've just got into the Sydney office and will be looking to make near-final changes over the next few hours. You available for a call to chat through any final elements?

**Comment by HPaulJohnson** [comment]
@rohanporteous - @lovegushwa and I are available now to jump in vidyo if you'd like (not sure of @brettgaylor's status).

**Comment by brettgaylor** [comment]
Can't do call but can respond to issues here tonight.

**Comment by OpenMatt** [comment]
Given that we are now working to finalize final cut, let's close this issue and manage final approvals here:  https://github.com/MozillaFoundation/encryption_campaign/issues/64
