### ISSUE TITLE
Write video script for beat 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#6]
cc @HPaulJohnson @rohanporteous

**Comment by OpenMatt** [comment]
@brettgaylor this is currently the top priority ticket for the entire project. so let's train all guns on this one.

**Comment by brettgaylor** [comment]
## Script draft

### Is here: http://mzl.la/beat1_script

we’ll need to decide how to do the “reveals” of the secrets the main character discovers.  There are 3 possibilities here:

#### 1) Do a fairly simple “computer interface” approach, similar to these benchmarks:

https://www.youtube.com/watch?v=B6zVzWU95Sw
https://www.youtube.com/watch?v=uFfq2zblGXw

The secrets would be displayed on these interfaces, though the primary character would need to see them somehow. So not Sherlock style, exactly - it would need to be diegetic.

#### 2) Riff on the character that we are creating for the 2nd beat (code name Crpty)

https://docs.google.com/document/d/1EU1soGsqlP793twPlusFUkfv2gYQ5ZKWke5Ho-TrD7M/edit
The idea here would be to have a “mean" character appear that reveals the secrets and displays them in a more animated style - you can see some early drafts of this action towards the bottom of the script in Sara’s early draft.

Or

#### 3) Have a human character oddly appear and announce the secret.

I think #1 is the most straightforward approach. #3 is a bit fraught is Mozilla marketing tried this approach in another campaign and it was not a success https://www.youtube.com/watch?v=BWZCi_OJiNA

**Comment by OpenMatt** [comment]
@brettgaylor outstanding work. what's the next step here? Who needs to do what next? 
cc @rohanporteous

**Comment by OpenMatt** [comment]
Key questions for @rohanporteous 
* your general thoughts on general direction we are taking based on script sara and i wrote
* can you shoot this in Sydney? does this feel doable for you?

**Comment by OpenMatt** [comment]
## Main high-level notes on draft 0.2
- 1) **Needs a stronger ending.** This is the main creative challenge for this beat / video: the call to action. Come back with options for stronger candidate endings. 
- 2) **Green light on the opening story.** Need to test and nail the examples, but so far so good on the general approach for act 1. 
- 3) **Need to test / think about the semantics.** e.g., “secrets” vs. “privacy.” These words and frames are highly charged, and elicit strong (often conflicting) emotional reactions from people. We want to be explicit about word-smithing and testing. (And ideally: have some data or research to inform our choices.)

Those seems to be the main pieces of work to do for version 0.3. Still need feedback from Acency.

**Comment by OpenMatt** [comment]
### Next steps from Agency

Rohan: 
- [ ] 1) Rohan will take a look at the script 
- [ ] 2) They will assess whether the script is feasible for shooting / delivering by deadline. Figure out answers to the feasibility questions between the Syd/NY offices.
- [ ] 3) Potentially get Tom to do a rewrite focusing on a stronger ending if he has time in his schedule.

**Comment by OpenMatt** [comment]
#### re: testing language
- re: testing of language. We’ll probably want 2-3 different versions of the video that we segment based on language variations.

**Comment by OpenMatt** [comment]
@brettgaylor note that @rohanporteous has made a bunch of comments in the google doc

**Comment by rohanporteous** [comment]
Hey guys, sorry for the slightly haphazard and lengthy notes below! Have a read through and let me know what you think. Could possibly jump on a call between 7/8 this evening if that works for you.

Thanks!
R

## Concept/project management

**Treatment**: one of the main reasons for the switch in concepts was a switch away from live action to motion graphics/something more flexible wasn’t it? Is that no longer a concern? This introduces more characters and (possibly) locations which both takes longer to do and is a bigger push in a small amount of time, so increases what you were calling the risk of not being able to change things later. Would just be good to understand the reasoning here. 

Going back to live action means we're definitely a little more behind as we were trying to get the ball rolling on all talent/location/crew last week, whereas now it's much harder to follow up on. But that doesn't mean that it's impossible of course ;) 

I also wasn't 100% clear on how you were imagining the story would come across. Were you thinking that she would be walking past all of these characters/scenes in the one space, slightly separate from the reality of how she'd interact with them? (This comes across in the 'looking back to all characters'). Or were you thinking something more naturalistic, real scenes in different real-world locations with text overlays? (Hinted at with the notion Sydney might be a bit prettier/work better than NYC). Probably good to keep both options open.

Brett's questions on **Production/Timezones**: I'm currently in PST. The new treatment going back to live action and a more complicated shoot admittedly makes me a bit nervous as well, as I was thinking your last notes meant we were headed towards something that was more akin to the stock footage with motion graphics treatment in the original, as mentioned up top. (Hence the original push to have concept locked last week). But again, that doesn't make it impossible. It just means that we'll have to work with more speed and flexibility next week :)

Tom _might_ be able to take this on, but I have to follow up with him around lunchtime today. He's currently only scheduled scripting time, not broader project management or, of course, the possibility of taking on the project in full. Will let you know how our chat goes.

**Next Steps**: pending the update on Tom possibly having more involvement than originally intended, he will be able to get a new version of the script for us to discuss tomorrow morning. I could jump on a call with you at 8am if you're available? Otherwise could just send it through with my notes. I'll chase some of our previous leads for crew this evening as well, and see what work we can get happening with locations this week.

## Script notes

Already mentioned some of these in the doc comments, but thought I'd include here as well.

**Focus**: Do we need to introduce the central conceit earlier? Doesn't have to be 'encryption' per se, but possibly the question around it being ok/not to give the government access, or if it matters/not if we protect it properly. At the moment it feels quite broad around secrets/privacy, and not about protection. But could simply make that stronger towards the end.

**Secrets**: mentioned by your team a number of times, but I think the shift away from ‘secrets’ to privacy/everyday information (while still addressing that initial premise). If we do need to mention secrets we need to blow the idea apart even more than here where it still sounds suspect. The point being that people need to realize that secrets aren't 'secrets', but are simply bits of information. (My mention of language was actually meant to refer to this—secrets VS privacy etc—rather than actual languages. Sorry for the confusion!)

**Crypty**: doesn’t really make too much sense to me as a random insert towards the end, and possibly adds more confusion than the value it adds. Guessing he’s meant to be like Microsoft’s Clippy? Unless going for tongue-in-cheek character I would question that kind of character’s value and appreciation by the audience. Not sure what you're thinking for beat 2 but would go with something a bit off the wall, like these guys: https://www.youtube.com/watch?v=Bt9zSfinwFA. But depends on the tone you're after of course ;)

**CTA**: as noted, needs something more compelling than ’multi-week education initiative’. Need to know how encryption is threatened, and that there signing up can help to protect it. (Even if it’s as simple as something like ‘right now, encryption is under threat, putting your privacy is at stake. Sign up now to find out how you can protect encryption, and the privacy of everyday people all over the world’. (Lines like ‘fill in your email address’ are also a bit too passive and technical, when sign up/join are also fine).

**Comment by OpenMatt** [comment]
thanks @rohanporteous. @brettgaylor, over to you to discuss w. team and post feedback here.

**Comment by brettgaylor** [comment]
> > Treatment: one of the main reasons for the switch in concepts was a switch away from live action to motion graphics/something more flexible wasn’t it? Is that no longer a concern? This introduces more characters and (possibly) locations which both takes longer to do and is a bigger push in a small amount of time, so increases what you were calling the risk of not being able to change things later. Would just be good to understand the reasoning here.

My thinking there was that a) you had responded saying that motion graphics were more of a capacity drain for you guys, and b) We were more concerned with the "one take" nature of the other concept.  Feeling was that as the piece was coming together, there was more room to have flexibility in the edit suite with this approach.

Re: multiple locations/cast - I think you guys should look at the script and make edits based on your capacity.  If you want to keep locations and characters down to keep this in the doable range, we get that.  I wanted to present something that could be shot in a single day.

> > I also wasn't 100% clear on how you were imagining the story would come across. Were you thinking that she would be walking past all of these characters/scenes in the one space, slightly separate from the reality of how she'd interact with them? (This comes across in the 'looking back to all characters'). Or were you thinking something more naturalistic, real scenes in different real-world locations with text overlays? (Hinted at with the notion Sydney might be a bit prettier/work better than NYC). Probably good to keep both options open.

We were assuming the 2nd option.

> > Brett's questions on Production/Timezones: I'm currently in PST. The new treatment going back to live action and a more complicated shoot admittedly makes me a bit nervous as well, as I was thinking your last notes meant we were headed towards something that was more akin to the stock footage with motion graphics treatment in the original, as mentioned up top. (Hence the original push to have concept locked last week). But again, that doesn't make it impossible. It just means that we'll have to work with more speed and flexibility next week :)

OK, understood.  Again, our intention was to pitch you guys something that felt attainable, and our question re: the week was whether Tom could be on point for coming back to us, getting a script together and giving a thumbs up/down on the feasibility of the live action proposed.

> Otherwise could just send it through with my notes. I'll chase some of our previous leads for crew this evening as well, and see what work we can get happening with locations this week.

That sounds great, Rohan.  And maybe between now and Friday, if we could find some time either evening or morning pacific time to catch up on someone from Agency that feels right to you, we'd appreciate that.  The purpose of that meeting would essentially be go/no go and next steps.

> > Secrets: mentioned by your team a number of times, but I think the shift away from ‘secrets’ to privacy/everyday information (while still addressing that initial premise). If we do need to mention secrets we need to blow the idea apart even more than here where it still sounds suspect. The point being that people need to realize that secrets aren't 'secrets', but are simply bits of information. (My mention of language was actually meant to refer to this—secrets VS privacy etc—rather than actual languages. Sorry for the confusion!)

Yes, everyone has strong feels about this :)  It's where we need to keep iterating a script, and also where we thought "hey maybe we should do some learning here, and produce a few variants where narrator tries different language and A/B test"

> > Crypty: doesn’t really make too much sense to me as a random insert towards the end, and possibly adds more confusion than the value it adds.

Heh if he comes across as clippy, epic fail :)  He's the main focus of beat 2, and yeah more of an off the wall / irreverent approach. The idea was to try and use him as a bridge, but really we don't necessarily need to.  @shaghdoosti was excited about the concept of multiple characters for beat 1, but this could be a stretch with both the internal coherence of the piece and our capacity.  We'd be happy to leave that call to you!

And we absolutely agree w/ you re: CTA.

Thanks for these detailed notes - they're very appreciated!

**Comment by rohanporteous** [comment]
Hey guys,

Tom worked through a script yesterday and some of my feedback last night, and we've now got this version to show you. We're trying to keep it focused around a smaller number of locations, and have a central character throughout like your initial draft.

While we normally hand over more complete drafts, I've left this one with my notes in it so you can see some of the current things we're working through. Happy to hear thoughts/comments on anything/everything, and looking forward to talking with you later in the day! (5:30 works for me).

Thanks!
R

https://docs.google.com/document/d/1bd_gMQb5Pqil5Eui8a1VzoleHZLGgwFcRVBwK_NJVW4/edit?usp=sharing

**Comment by jgmac1106** [comment]
Make sure to run the script by a diverse audience before producing. It
didn't come off bad to me but the story begins with a women in bathroom,
followed by some NSFW sexting and then shopping for lingerie.

I am worried this could be perceived as focusing on very engendered
practice. Why is the privacy a women needs focused on they way she wants to
please her man?

Just a thought. As said I think it came off okay but I would pass the
script around to people focused on gender and diversity issues before going
to production.

**Comment by OpenMatt** [comment]
thanks @rohanporteous -- @brettgaylor will get back w. feedback asap

**Comment by jgmac1106** [comment]
In fact i would just switch to a more neutral topic like medicine. Instead
of starting in the bathroom start at the Dr's office. Instead of sexting
she shares "some news" with a friend. Maybe instead of shopping for
lingerie and "sheer lace playsuits" she searches for medical information.

The script would still work but you would lose the gender and sexuality
theme. We need privacy so we can "sext" is just a poor sell IMO.

Plus it would not play in more conservative areas we are trying to reach.
Imagine the teacher in Indonesia or a rep in India trying to show a video
about a women trying to get "rumpy pumpy tonight."

Finally try to avoid the colloquial humor (probably humor in general) as it
never translates well.

**Comment by OpenMatt** [comment]
@jgmac1106 thanks for the feedback! I've moved it to this ticket https://github.com/MozillaFoundation/encryption_campaign/issues/18 so that this one doesn't get too long / more complex than it already is.

**Comment by rohanporteous** [comment]
Totally agreed Greg! This was something I was discussing with Tom, would
love to remove that element entirely. (This script doesn't take all those
comments on board at the moment).

I think that the cute/silly sexting could possibly be ok if we test a few
different types of messages, but don't want to focus the rest of her goals
around that moment.

Good to see we're on the same page ;)

On Wednesday, January 13, 2016, Greg McVerry notifications@github.com
wrote:

> Make sure to run the script by a diverse audience before producing. It
> didn't come off bad to me but the story begins with a women in bathroom,
> followed by some NSFW sexting and then shopping for lingerie.
> 
> I am worried this could be perceived as focusing on very engendered
> practice. Why is the privacy a women needs focused on they way she wants to
> please her man?
> 
> Just a thought. As said I think it came off okay but I would pass the
> script around to people focused on gender and diversity issues before going
> to production.
> 
> On Wed, Jan 13, 2016 at 10:47 AM Rohan Porteous <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Hey guys,
> > 
> > Tom worked through a script yesterday and some of my feedback last night,
> > and we've now got this version to show you. We're trying to keep it
> > focused
> > around a smaller number of locations, and have a central character
> > throughout like your initial draft.
> > 
> > While we normally hand over more complete drafts, I've left this one with
> > my notes in it so you can see some of the current things we're working
> > through. Happy to hear thoughts/comments on anything/everything, and
> > looking forward to talking with you later in the day! (5:30 works for
> > me).
> > 
> > Thanks!
> > R
> > 
> > https://docs.google.com/document/d/1bd_gMQb5Pqil5Eui8a1VzoleHZLGgwFcRVBwK_NJVW4/edit?usp=sharing
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/MozillaFoundation/encryption_campaign/issues/6#issuecomment-171337457
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/6#issuecomment-171341102
> .

## 

Rohan Porteous
Creative Director

http://agency.sc
The creative studio for social change · Sydney · New York
office +1 (646) 583-1538 · cell +1 (646) 932-7169
address  601 West 26th #325 · skype rohanporteous

**Comment by rohanporteous** [comment]
Ah. Didn't see your other note RE medicine etc. I think it doesn't have to
be 'sexting' by any means, but I think it's possibly powerful to cover the
privacy inherit in relationships in some ways. Is there something that our
conservative audiences would share as a couple that they wouldn't want out
in the public (that also works as something funny or compelling)?

On Wednesday, January 13, 2016, Rohan Porteous rohan@agency.sc wrote:

> Totally agreed Greg! This was something I was discussing with Tom, would
> love to remove that element entirely. (This script doesn't take all those
> comments on board at the moment).
> 
> I think that the cute/silly sexting could possibly be ok if we test a few
> different types of messages, but don't want to focus the rest of her goals
> around that moment.
> 
> Good to see we're on the same page ;)
> 
> On Wednesday, January 13, 2016, Greg McVerry <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Make sure to run the script by a diverse audience before producing. It
> > didn't come off bad to me but the story begins with a women in bathroom,
> > followed by some NSFW sexting and then shopping for lingerie.
> > 
> > I am worried this could be perceived as focusing on very engendered
> > practice. Why is the privacy a women needs focused on they way she wants
> > to
> > please her man?
> > 
> > Just a thought. As said I think it came off okay but I would pass the
> > script around to people focused on gender and diversity issues before
> > going
> > to production.
> > 
> > On Wed, Jan 13, 2016 at 10:47 AM Rohan Porteous <notifications@github.com
> > 
> > > wrote:
> > > 
> > > Hey guys,
> > > 
> > > Tom worked through a script yesterday and some of my feedback last
> > > night,
> > > and we've now got this version to show you. We're trying to keep it
> > > focused
> > > around a smaller number of locations, and have a central character
> > > throughout like your initial draft.
> > > 
> > > While we normally hand over more complete drafts, I've left this one
> > > with
> > > my notes in it so you can see some of the current things we're working
> > > through. Happy to hear thoughts/comments on anything/everything, and
> > > looking forward to talking with you later in the day! (5:30 works for
> > > me).
> > > 
> > > Thanks!
> > > R
> > > 
> > > https://docs.google.com/document/d/1bd_gMQb5Pqil5Eui8a1VzoleHZLGgwFcRVBwK_NJVW4/edit?usp=sharing
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/MozillaFoundation/encryption_campaign/issues/6#issuecomment-171337457
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MozillaFoundation/encryption_campaign/issues/6#issuecomment-171341102
> > .
> 
> ## 
> 
> Rohan Porteous
> Creative Director
> 
> http://agency.sc
> The creative studio for social change · Sydney · New York
> office +1 (646) 583-1538 · cell +1 (646) 932-7169
> address  601 West 26th #325 · skype rohanporteous

## 

Rohan Porteous
Creative Director

http://agency.sc
The creative studio for social change · Sydney · New York
office +1 (646) 583-1538 · cell +1 (646) 932-7169
address  601 West 26th #325 · skype rohanporteous

**Comment by jgmac1106** [comment]
If only ideas came as easy as critique....

Funny is hard. I did not mean the literal translations but the idioms and
double meanings never work well for people with English as a second
language.

I just meant the Dr. because the bathroom could be the office where someone
wants privacy. Keeping medical data private might motivate people
Maybe:
-surprise party
-engagement
-pregnancy
