### ISSUE TITLE
Create internal marketing deck for campaign

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#78]
(Using the story arc and narrative from #67)
This ticket will be to create a deck for sharing across multiple internal moco and mofo stakeholders.

**Comment by OpenMatt** [comment]
@valianttry will finish and share in prep for campaign launch

**Comment by valianttry** [comment]
I have created a deck here:
https://docs.google.com/presentation/d/11h5S2DQYn8RYkLqNzfXAkUrM0EkXOcIhRaCnDJ5CyE4/edit#slide=id.ga39cad493_0_10

It is a master document that can be shortened or re-arranged for different audiences. The opening slides are a "zoomed out" view for those who are less familiar with grassroots advocacy.
- Mark reviewed this deck. I incorporated his feedback.
- @shaghdoosti reviewed it and gave :+1: 
- @HPaulJohnson  and @KevZawacki are taking a look.
- @brettgaylor and @OpenMatt can you also look it over?

**Comment by brettgaylor** [comment]
Bit of a driveby, sorry!

I think this works for the campaign.  Provides a good level of detail on our experiments as well as the nuance of the "committed" audience goals and KPIs.

I think an area where it doesn't necessarily paint a full picture is how this campaign is giving people ways to talk about and understand these issues that the market currently lacks.  This is touched on a bit in the deck:

> If the vast majority of people have no idea that encryption is worth protecting, how can we expect them to stand up for it when it matters most?

But I think we can expand on this: benchmarks, showing creative choices, etc - would be happy to hack on this over the course of the campaign, or speak to it wherever we're planning to show this deck.

Also - since this deck hints at our overall strategy,  I'd love to see us iterate on what actions we imagine our advocates taking.  Right now we give the sense that we want to be impactful in terms of providing urgency to legislative/policy positions. I think that should be one, and likely a primary, advocacy goal - but I think we'll have other goals of influencing social norms, markets, code, etc.  What kind of actions can our advocates take to move these areas of influence? Likely outside of encryption campaign scope, but this deck is also describing our larger goals so it stands out for me.

Nice one!

**Comment by KevZawacki** [comment]
@valianttry Left only a few minor comments. Really clear and smart! :+1:

**Comment by valianttry** [comment]
@brettgaylor good points --
- I agree we should mention that we're solving a very pervasive problem in the market not only for us, but for many partners in this movement (availability of quality helpful content about complicated Internet issues). Will add.
-  it might be worth it to spend a slide talking about our philosophy behind "share" as a core CTA for the "market / culture shift" piece. I'll also mention we are fully aware culture change is difficult to measure (and "# of shares" isn't that helpful), but it's worth trying to measure because it's vitally important for our theory of change long-term.

**Comment by brettgaylor** [comment]
>  I'll also mention we are fully aware culture change is difficult to measure (and "# of shares" isn't that helpful)

Yes I think digging into this piece is both important for the deck, and a really great piece of work moving forward and one where we have allies. (:+1:)

**Comment by OpenMatt** [comment]
Closing. @valianttry please re-open if that's wrong.
